# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.feature_voter:
        class: AppBundle\Security\FeatureVoter
        arguments:
            - @file_locator
            - @security.access.decision_manager
        tags:
            - { name: security.voter }
        public: false